---
# handlers file for deploy_httpd
- name: Restart httpd Redhat
  service: name=httpd state=restarted
  when: ansible_os_family == "RedHat"

- name: Restart httpd Debian
  service: name=apache2 state=restarted
  when: ansible_os_family == "Debian"

- name: Restart httpd Ubuntu
  service: name=apache2 state=restarted
  when: ansible_os_family == "Ubuntu"


